//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 AirCraftCasingVibrateSystem.rc 使用
//
#define ID_BMPSIGNALRED                 3
#define IDOK2                           3
#define ID_EU_SAVE                      3
#define IDCANCEL2                       4
#define IDOK3                           5
#define ID_SAVE_BUTTON                  5
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_AIRCRAFTCASINGVIBRATESYSTEM_FORM 101
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_AirCraftCasingVTYPE         130
#define ID_WINDOW_MANAGER               131
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define ID_TOOLS_OPTIONS                220
#define ID_VIEW_CAPTION_BAR             221
#define IDB_INFO                        230
#define IDS_CAPTION_BUTTON              231
#define IDS_CAPTION_BUTTON_TIP          232
#define IDS_CAPTION_TEXT                233
#define IDS_CAPTION_IMAGE_TIP           234
#define IDS_CAPTION_IMAGE_TEXT          235
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDD_DIALOG_ALARM                310
#define IDD_DIALOG_CHANNEL_PARA         311
#define IDD_DIALOG_DEVICE_PARA          312
#define IDD_DIALOG_ENGINEER_UINT        313
#define IDD_DIALOG_GENERAL_PARA         314
#define IDD_DIALOG_GEOMETRIC_PARA       315
#define IDD_DIALOG_GRAPHIC_ATTRIBUTE    316
#define IDD_DIALOG_LOGIN                317
#define IDD_DIALOG_SERSOR_PARA          318
#define IDD_DIALOG_SIGNAL_SAVE          319
#define IDD_DIALOG_SUB_CHANNEL_PARA     320
#define IDD_DIALOG_SYSTEM_PARA          321
#define IDD_DIALOG_TRIGGER_PARA         322
#define IDD_DIALOG1_DATA_STATISTIC      323
#define IDI_START                       327
#define IDR_MENU_RIGHT_KEY              339
#define IDD_DIALOG_SIGNAL_SELECT        340
#define IDB_BMPCONTRLBIG                344
#define IDB_BMPCONTRLSMALL              346
#define IDB_BMPFILEBIG                  347
#define IDB_BMPSYSTEMBIG                348
#define IDB_BMPSIGNALGREEN              349
#define IDD_DIALOG_GRAPH_ATRR           351
#define IDD_DIALOG_CORLOR               352
#define IDD_DIALOG_FONT                 353
#define IDD_DIALOG_LINE                 354
#define IDD_DIALOG_SELECT               355
#define IDD_DIALOG_COORDINATE           356
#define IDD_DIALOG_New_PROJECT          357
#define IDD_DIALOG_ALARM_PARA_SET       358
#define IDD_DIALOG_PROJECT_MANAGE       359
#define IDD_DIALOG_OPEN_DATA            361
#define IDD_DIALOG_DETECT_DEVICE_MANAGE 362
#define IDD_DIALOG_DETECTED_DEVICE_MANAGE 363
#define IDD_COLLECTIONDATAINFO_DIALOG   368
#define IDD_PROJECTBASEINFO_DIALOG      371
#define IDD_DIALOG_COLLECTIONPARAPRESET 372
#define IDD_DIALOG_CHANNEL_PARA_SELECT_AND_SET 373
#define IDD_DIALOG_STABLESTATUSPRESET   374
#define IDD_DIALOG_STATE_SET            377
#define IDD_DIALOG_REGISTER             379
#define IDD_DIALOG_COLLECTIONPLANMANAGE 382
#define IDD_DIALOG_PROJECTSET           383
#define IDC_TAB1                        1000
#define IDC_LIST_GENERAL_PARA           1001
#define IDC_COMBO1                      1002
#define IDC_COMBO2                      1003
#define IDC_TAB_SYSTEM_PARA             1004
#define IDC_LIST_TRIGGER_PARA           1005
#define IDC_COMBO3                      1006
#define IDC_COMBO4                      1007
#define IDC_COMBO5                      1008
#define IDC_COMBO6                      1009
#define IDC_COMBO7                      1010
#define IDC_COMBO8                      1011
#define IDC_TREE_SELECTED_CHANNEL       1012
#define IDC_LIST1                       1013
#define IDC_TREE_SELECT_CHANNEL2        1013
#define IDC_TREE_SELECT_CHANNEL         1013
#define IDC_EDIT_PROJECTNAME            1014
#define IDC_EDIT2                       1015
#define IDC_EDIT_PASSWORD               1015
#define IDC_BUTTON_EU_ADD               1016
#define IDC_CHECK1                      1017
#define IDC_CHECK_CHANNEL_ALARM         1017
#define IDC_TAB_GRAPH_ATTR              1018
#define IDC_EDIT_LOGNNAME               1019
#define IDC_COMBO_TESTINGDEVICE         1020
#define IDC_COMBO_DETECTEDDEVICE        1021
#define IDC_COMBO_PRODUCT               1021
#define IDC_BUTTON2                     1024
#define IDC_TAB_ENGINEER_UNIT           1025
#define IDC_CHECK2                      1026
#define IDC_CHECK_ALARM_LOG             1026
#define IDC_EDIT1                       1027
#define IDC_CHECK3                      1028
#define IDC_DATETIMEPICKER1             1029
#define IDC_SIGNALDATASTARTTIME         1029
#define IDC_DATETIMEPICKER2             1030
#define IDC_SIGNALDATAENDTIME           1030
#define IDC_MFCBUTTON1                  1031
#define IDC_SEARCHBUTTON                1031
#define IDC_MFCBUTTON_WIN_BG            1031
#define IDC_BUTTON3                     1033
#define IDC_GRIDCTRL_PROJECT            1034
#define IDC_MFCBUTTON_GRAPH_BG          1048
#define IDC_MFCBUTTON_INF_BG            1049
#define IDC_MFCBUTTON_SERIS1_BG         1051
#define IDC_MFCBUTTON_SERIS2_BG         1052
#define IDC_MFCBUTTON_SERIS33_BG        1053
#define IDC_MFCBUTTON_SERIS4_BG         1054
#define IDC_MFCBUTTON_GRID_BG           1055
#define IDC_MFCBUTTON_COOR_BG           1056
#define IDC_MFCBUTTON_SCALE_BG          1057
#define IDC_MFCBUTTON_CURLOR_BG         1058
#define IDC_MFCBUTTON_X_BG              1060
#define IDC_MFCBUTTON_Y_BG              1062
#define IDC_MFCBUTTON_STATISC_BG        1063
#define IDC_RADIO1                      1064
#define IDC_RADIO2                      1065
#define IDC_RADIO3                      1066
#define IDC_RADIO4                      1067
#define IDC_RADIO7                      1070
#define IDC_RADIO8                      1071
#define IDC_LIST3                       1074
#define IDC_LIST4                       1075
#define IDC_EDIT3                       1076
#define IDC_LIST5                       1077
#define IDC_RADIO5                      1078
#define IDC_RADIO6                      1079
#define IDC_LIST2                       1080
#define IDC_CHECK4                      1082
#define IDC_CHECK_SOUND_ALARM           1082
#define IDC_CHECK5                      1083
#define IDC_CHECK_MAX_VALUE             1083
#define IDC_CHECK6                      1084
#define IDC_CHECK_MIN_VALUE             1084
#define IDC_CHECK7                      1085
#define IDC_CHECK_EFFECTIVE_VALUE       1085
#define IDC_CHECK8                      1086
#define IDC_CHECK_MEAN_VALUE            1086
#define IDC_EDIT4                       1087
#define IDC_EDIT_PROSEARCHNAME          1088
#define IDC_DATESEARCH_CHECKBOX         1089
#define IDC_PROSTARTTIME                1090
#define IDC_PROENDTIME                  1091
#define IDC_SIGNALDATA_GRIDCTRL         1092
#define IDC_SIGNALDATANAME_EDIT         1093
#define IDC_PROJECTNAME_EDIT            1093
#define IDC_SEARCH_BUTTON               1094
#define IDC_DATESELECT_CHECK            1095
#define IDC_GENERAPARA_GRIDCTRL         1096
#define IDC_TESTINGDEVICE_GRIDCTRL      1097
#define IDC_TESTINGDEVICENAME_EDIT      1098
#define ID_DELETE_BUTTON                1099
#define IDC_ADD_BUTTON                  1100
#define IDC_PRODUCTNAME_EDIT            1103
#define IDC_ROTATINGSPEED_EDIT          1104
#define IDC_DATE_COMBO                  1105
#define IDC_TRIGGERPARA_GRID            1107
#define IDC_GEOMETRICPARA_GRIDCTRL      1108
#define IDC_TREE1                       1109
#define IDC_BUTTON4                     1111
#define IDC_BUTTON_NEXTSTEP             1111
#define IDC_BUTTON_X_UNIT               1111
#define IDC_BUTTON_ADDPLANPARAROW       1111
#define IDC_PROJECTPLAN_GRID            1113
#define IDC_COMBO_COLLECTIONFREQUENCY   1116
#define IDC_COMBO_COLLECTIONMETHOD      1117
#define IDC_COMBO_ANALYSISFREQUENCY     1118
#define IDC_COMBO_TRIGGERMETHOD         1119
#define IDC_COMBO_DATABLOCKCOUNT        1120
#define IDC_COMBO_TRIGGERCOUNT          1121
#define IDC_COMBO_DELAYBLOCKCOUNT       1122
#define IDC_COMBO_SAMPLINGBATCH         1123
#define IDC_BUTTON_LASTSTEP             1125
#define IDC_GRIDCTRL_CHANNELPARA        1126
#define IDC_GRIDCTRL_STABLESTATUSPARA   1127
#define IDC_BUTTON_ADD                  1128
#define IDC_EDIT_DELAYBLOCKCOUNT        1129
#define IDC_CHECK_APP_ALL_WIN           1129
#define IDC_EDIT_COLLECTIONBATCH        1130
#define IDC_EDIT_TRIGGERCOUNT           1131
#define IDC_BUTTON_Y_UNIT               1131
#define IDC_BUTTON_OK                   1133
#define IDC_BUTTON_STATISTIS_INF        1133
#define IDC_BUTTON_CANNEL               1134
#define IDC_BUTTON_CANCEL               1134
#define IDC_BUTTON_TEXT_INF             1134
#define IDC_BUTTON9                     1135
#define IDC_BUTTON_PROJECT_INF          1135
#define IDC_BUTTON_XCOOR                1136
#define IDC_BUTTON_YCOOR                1137
#define IDC_BUTTON_CURSOR_VALUE         1138
#define IDC_BUTTON_CURSOR_MARK          1139
#define IDC_CHECK_GRID_LINE             1140
#define IDC_CHECK_STATISTIC_INF         1141
#define IDC_CHECK_PEAK_VALUE            1142
#define IDC_EDIT_COLLECTIONBATCHS       1143
#define IDC_CUSTOM_EU                   1144
#define IDC_PLAN_PARA                   1144
#define IDC_COLLECTIONPLANGRID          1145
#define IDC_MFCBUTTON2                  1146
#define IDC_COMBO_COLLECTIONPLAN        1147
#define IDC_PRODUCT_MANAGE              1148
#define ID_SAVE_PRODUCT                 1150
#define IDC_BTN_SEARCH_PRODUCT          1151
#define IDC_EDIT_ALARM_LIMIT            1152
#define ID_SAVR_ALARM_SET               1153
#define ID_REGISTER                     1154
#define IDC_EDIT_REGISTER_USER_NAME     1155
#define IDC_EDIT_REGISTER_PSW           1156
#define IDC_EDIT_REGISTER_POST          1157
#define IDC_EDIT_REGISTER_TELL          1158
#define IDC_EDIT_REGISTER_NAME          1159
#define IDC_EDIT_REGISTER_QPSW          1160
#define IDC_BUTTON_LOGINVIEW_REGISTER   1161
#define IDC_BUTTON_EU_DELETE            1162
#define IDC_COMBO_PRODUCT_NAME          1167
#define IDC_COMBO_PROJECT_NAME          1168
#define IDC_COMBO_PLAN_NAME             1169
#define IDC_STATIC_CUR_PLAN_PARA        1170
#define IDC_BUTTON_ADDPLANBASEINFO      1171
#define IDC_BUTTON_ADDPLANPARACOL       1172
#define IDC_BUTTON_DELPLANPARAROW       1173
#define IDC_GRIDCTRL_COLLECTIONPLANBASEINFO 1174
#define IDC_GRIDCTRL_COLLECTIONPARAINFO 1175
#define IDC_BUTTON_SAVEPLANPARA         1176
#define IDC_BUTTON_DELPLANBASEINFO      1177
#define IDC_BUTTON_SAVEPLANBASEINFO     1178
#define IDC_TAB_PROJECT_NAVIGATION      1181
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_CHECK2                       32771
#define ID_COMBO2                       32772
#define ID_CHECK3                       32773
#define ID_VIEW_CHANNELPARA_BAR         32773
#define ID_BUTTON_START_CAPTURE         32774
#define ID_BUTTON_SUSPEND_CAPTURE       32775
#define ID_BTN_STOP_CAPTURE             32776
#define ID_BTN_START_PLAYBACK           32777
#define ID_SLIDER1                      32778
#define ID_BTN_STOP_PLAYBACK            32779
#define ID_BTN_CLOSE_ALL_WINDOW         32784
#define ID_BTN_TRANSVERSE_AMPLIFICATION 32785
#define ID_BTN_HORIZONTAL_REDUCTION     32786
#define ID_BTN_VERTICAL_AMPLIFICATION   32787
#define ID_BTN_VERTICAL_REDUCTION       32788
#define ID_BTN_SINGLE_CURSOR            32789
#define ID_BTN_NO_CORROR                32790
#define ID_BTN_PEAK_VALUE               32791
#define ID_BUTTON_NEW_PROJECT           32792
#define ID_BUTTON2_SAVE_PROJECT         32793
#define ID_BUTTON_PROJECT_MANAGE        32794
#define ID_BTN_GRAPH_ATTR               32795
#define ID_BUTTON23                     32796
#define ID_BUTTON24                     32797
#define ID_BUTTON_OPEN_DATA_FILE        32798
#define ID_BUTTON_EXPORT_CHANNEL_PARA   32799
#define ID_BUTTON_EXPORT_SYS_PARA       32800
#define ID_BUTTON_IMPORT_CHANNEL_PARA   32801
#define ID_BUTTON_IMPORT_SYS_PARA       32802
#define ID_BUTTON_SIGNAL_SELECT         32803
#define ID_BTN_PROJECT_UNIT             32804
#define ID_BTN_ALARM_SET                32805
#define ID_BUTTON33                     32806
#define ID_BUTTON34                     32807
#define ID_BUTTON8                      32808
#define ID_BUTTON35                     32809
#define ID_BUTTON36                     32810
#define ID_32811                        32811
#define ID_32812                        32812
#define ID_32813                        32813
#define ID_32814                        32814
#define ID_32815                        32815
#define ID_32816                        32816
#define ID_32817                        32817
#define ID_BTN_AUTO_SCALE               32818
#define ID_BTN_SELF_SCALE               32819
#define ID_BTN_START_SMAPLE             32820
#define ID_BTN_STOP_SAMPLE              32821
#define ID_BUTTON2                      32824
#define ID_BUTTON3                      32825
#define ID_BUTTON4                      32826
#define ID_BUTTON_DETECT_DEVICE         32827
#define ID_BUTTON_DETECTED_DEVICE       32828
#define ID_32829                        32829
#define ID_COMBO3                       32830
#define ID_COMBO4                       32831
#define ID_BUTTON5                      32837
#define ID_BUTTON6                      32838
#define ID_BUTTON7                      32839
#define ID_BUTTON9                      32840
#define ID_CHECK_STA_SET                32841
#define ID_CHECK4                       32842
#define ID_VIEW_SYSTEMPARA_BAR          32842
#define ID_CHECK5                       32843
#define ID_BUTTON_OPENCOLLECTIONPLANMANAGE 32844
#define ID_BUTTON_OPENPROJECTVIEW       32845
#define ID_BUTTON_OPEN_PROJECTSET_VIEW  32846

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        384
#define _APS_NEXT_COMMAND_VALUE         32847
#define _APS_NEXT_CONTROL_VALUE         1182
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
